---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build-latest
  image: rust:latest
  commands:
  - cargo build --all-targets
  - cargo test

trigger:
  event:
    include:
    - push
